name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --no-restore --configuration Release

      - name: Publish application
        run: dotnet publish -c Release -o publish

      - name: Check GitHub context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::033026138018:role/GitHubActions-ECSPractice
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t ecs-practice:latest .

      - name: Tag Docker image
        run: |
          docker tag ecs-practice:latest 033026138018.dkr.ecr.us-east-1.amazonaws.com/ecs-practice:latest

      - name: Push Docker image to ECR
        run: |
          docker push 033026138018.dkr.ecr.us-east-1.amazonaws.com/ecs-practice:latest
